### ISSUE TITLE
Documentation: etcd Operator + bootkube

### ISSUE THREAD

**Issue by philips** [kubernetes-incubator/bootkube#240]
Just a quick guide on how to do this on AWS. Just telling me which files to edit is fine.

**Comment by aaronlevy** [comment]
The closest at this stage is a WIP branch:
https://github.com/kubernetes-incubator/bootkube/tree/multi-node-self-host-etcd

```
cd hack/multi-node && vagrant destroy -f &&  rm -rf cluster && ./bootkube-up
```

**Comment by philips** [comment]
@aaronlevy when are we going to merge this branch?

**Comment by aaronlevy** [comment]
@philips the wip branch as-is won't be used. It is mostly workarounds because we didn't have self-hosted flannel yet. My next project is to wrap up the initial self-hosted etcd work. It will build off the work in https://github.com/kubernetes-incubator/bootkube/pull/247 then hopefully it is just a matter of documenting and/or feature flagging self-hosted etcd in all hack/* examples.

**Comment by ericchiang** [comment]
Self-hosted etcd has been removed for now https://github.com/kubernetes-incubator/bootkube/issues/738

Closing for now until we decide to re-enable it.
