### ISSUE TITLE
checkpointer: should GC itself if installer no longer scheduled

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#253]
The checkpointer is deployed via a daemonset which "installs" a static manifest to the host.

If the checkpoint-installer is no longer scheduled to a node, the checkpointer should know how to GC itself (and all checkpoints).

**Comment by yifan-gu** [comment]
Today I have an idea about using the checkpointer to checkpoint itself so that we can get rid of the checkpointer installer.

Here is what it will look like in several scenarios:

### Scenario A: checkpoint pod get scheduled on node A as a daemonset
_t0:_ Checkpointer (call it C1) gets running
_t1:_ C1 checkpoint *and activate* itself by reading its own spec and saving to `/etc/kubernetes/manifests`
_t2:_ The static pod version of checkpoint starts (call it C2), C2 will wait on a flock held by C1 to avoid race.
_t3:_ C1 runs in a loop to keep creating checkpoints for other pods if necessary.

### Scenario B: node A reboots, but cannot reach API server
_t0:_ Kubelet starts
_t1:_ The static pod version of checkpoint (C2) starts and grabs the flock
_t2:_ C2 starts running the same loop as C1, and kicks off other checkpointed pods.

### Scenario C: node A reached API server
_t0:_ Daemonset version of checkpoint (C1) gets scheduled and started on node A
_t1:_ C1 waits on a flock held by C2
_t2:_ C2 keeps running [1]
_t3:_ If C1 gets descheduled from node A, then C2 will find it out and remove all checkpoints

During [1], if checkpoint's spec is changed on the API server, then C2 will checkpoint the new spec, and be restarted by kubelet. So the running and on-disk checkpoint specs are always the latest.

This is actually not very different from the `checkpoint installer + checkpointer` model. But by using only one image/pod, we can have the checkpoint to get its own pod spec from API server and get rid of the hidden manifest (see #206 )

The imperfect part is that user than will see 2 checkpointer pods running on each master node, with one being active, and one being stand-by.

**Comment by aaronlevy** [comment]
I think this is a really interesting idea!

As far as the 2 checkpointer pods - really we already have this problem. There is a "checkpoint-installer" and "pod-checkpointer" on every node.

Another option to get rid of the 2 checkpointer pods might be to implement something like "exit on lock-contention" for the checkpointed copy. This is what we did for the self-hosted kubelet, such that if it saw anything attempting to acquire the lock, it would exit - allowing the copy sourced from the api-server (when available) to take over.

This more or less covers https://github.com/kubernetes-incubator/bootkube/issues/206 - but we would still need to add (regardless of this change) some logic to the checkpointer to be aware that if it is to be GC'd it needs to clean up all other checkpoints before removing itself.

**Comment by yifan-gu** [comment]
> Another option to get rid of the 2 checkpointer pods might be to implement something like "exit on lock-contention" for the checkpointed copy. This is what we did for the self-hosted kubelet, such that if it saw anything attempting to acquire the lock, it would exit - allowing the copy sourced from the api-server (when available) to take over.

Had a little bit more thought on this: This implies the static checkpointer will have a slightly different config than the daemonset checkpointer because it needs to exit on contention.

**Comment by aaronlevy** [comment]
Yeah, and  I don't actually think exiting on lock contention is a valid solution - the checkpointer is special in that it always needs to be running a static copy (so it will come up on reboot without an api-server). So ignore my previous suggestion.

**Comment by aaronlevy** [comment]
This is closed by https://github.com/kubernetes-incubator/bootkube/pull/366 right?

**Comment by aaronlevy** [comment]
Yeah it does (I think it needs to  have "fixes" for github to pick up). Closed in: https://github.com/kubernetes-incubator/bootkube/pull/366
