### ISSUE TITLE
New approach to setup Kubernetes cluster with bootkube

### ISSUE THREAD

**Issue by adieu** [kubernetes-incubator/bootkube#297]
I've been playing with bootkube recently. Really like the self-hosted idea. Especially self-hosted etcd. Hosting etcd cluster in the Kubernetes cluster itself using `etcd-operator` will solve a lot of maintenance problems. Great work!

One thing I have noticed is that the installation process for different cloud platform is a little bit hacky. We use shell scripts and copy files between local computer and remote servers. New users might find this process hard to understand.

So I added bootkube support to [Archon](https://github.com/kubeup/archon) which is a cluster management system based on Kubernetes. I made a [bootkube example](https://github.com/kubeup/archon/tree/master/example/k8s-bootkube) which demonstrate the way to bootstrap a new cluster with self-hosted etcd using bootkube.

Currently the example is only for demo purpose. It ends with just one server running the control plane. I'm planning to improve it with master HA and multiple nodes. And we have to wait for [this issue](https://github.com/kubernetes/kubernetes/issues/39816) to enable gc.

But I think this example has already shown the power of bootkube and archon. I'm wondering if someone from the bootkube project could have a look at it. I really need some advice here.

Thanks a lot.

**Comment by aaronlevy** [comment]
Hi @adieu, thank you for the kind words!

You are right that the cloud-platform installation process is pretty hacky right now (essentially just the quickstart scripts). The main reason for this is that I didn't want bootkube to be prescriptive about how you actually launch your compute resources - because there are many ways this can be done successfully (cloud-provider specific like cloudFormation in AWS, or terraform, saltstack, ansible, chef, etc.)

Ultimately I think these tools, or tools like Archon, which are purpose built for cluster-management are going to be better at these tasks than bootkube (so lets rely on them, rather than re-building that functionality into bootkube itself). The quickstart guides really are meant to be examples of how bootkube could be incorporated into other cluster management tooling.

So it is great to hear you're integrating bootkube into a management tool (and that it's working for you)!

Is there any specific thing that you were looking for advice on?

**Comment by adieu** [comment]
I totally agree with you about the idea to make bootkube focusing on the bootstrap process and leaving the resource management part to other tools. We've already had too many tools in this area and much efforts are wasted when everyone is inventing their own wheel.

`render` and `start` are the two main functions for bootkube. In Archon, we tend to manage the `render` part and use only the `start` function to bring up the cluster. Do you think it's a proper use of bootkube? Since there's an overlap on the `render` part. Is it possible we could unify some efforts there?

Another thing is about user experience. I think the value of bootkube will be fully recognized  when it's delivered properly by a resource management system (like Archon). Because an easy to use and understandable experience will help users adopt the self-hosted idea. If you don't mind, I'm thinking about contributing a guide in the `hack/` folder describing how to use bootkube and Archon together to bootstrap a self-hosted Kubernetes cluster with ease. I'm totally ok to keep it in the Archon repo if you want to keep the bootkube repo simple.

**Comment by aaronlevy** [comment]
It is perfectly valid to just use `bootkube start` and manage the rendering step separately. Other projects already do this too (because they have specific needs for their own rendering steps).

Right now my vague guidelines would be: If it can make use of the existing init-master/init-worker scripts in hack - then it might be an okay addtion. My main concern is supportability. The project changes quickly - and I won't be able to validate that it works on X providers / systems between releases - which can lead to stale instructions / installation methods.

Another option might be adding a Documentation section on other projects which use Bootkube? Then we could link out to Archon and its scripts (and any other tools) from there.

**Comment by aaronlevy** [comment]
Maybe something like `Documentation/integrations.md` (example in the Clair project: https://github.com/coreos/clair/blob/master/Documentation/integrations.md)
