### ISSUE TITLE
Multi-node testing of self-hosted etcd cluster

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#343]
We have one node testing of self-hosted etcd (SHE) now. We need to extend that to multi node testing.

Test scenarios:
- etcd pod might be different from boot etcd
- scale to 3 etcd pods spread across 3 nodes

As far as I'm concerned on flannel, AWS/Tectonic, we need to open up firewall rules:
- outbound for temporary ports (>30k)
- inbound/outbound for etcd ports 2379 (client), 2380 (peer)
- inbound/outbound for temp port of boot etcd. Might not need if in temp port range.

**Comment by hongchaodeng** [comment]
@xiang90 @aaronlevy @ethernetdan

**Comment by ethernetdan** [comment]
@pbx0 has a test for this: https://github.com/coreos-inc/pluton/blob/master/tests/bootkube/scale.go

@hongchaodeng I believe the reason it didn't catch the issue I ran into is the Nodes join after the pivot to the etcd-operator managed Pod: https://github.com/coreos-inc/pluton/blob/master/tests/bootkube/scale.go#L37.

If we choose to allow bootstrapping in a multi-node scenario we should expand our coverage to include adding Nodes during bootstrap. I have mixed feelings about this because distributing the bootstrap adds complexity.

**Comment by aaronlevy** [comment]
FWIW the bootstrap has never been designed as requiring a single node.  Actually the opposite -- nodes should be able to be launched and register as soon as an api-server is available. This has always been true for the hack/multi-node example, which launches multiple nodes first, then runs the bootstrap. 

Restricting this to a single node actually adds (imo) more complexity because now we have to coordinate timed launching of resources.
