### ISSUE TITLE
Allow API server port selection

### ISSUE THREAD

**Issue by odacremolbap** [kubernetes-incubator/bootkube#354]
Currently API Server ports are set to 443 and 8080.
In my scenario, port 443 at master is used by an ingress controller.

To allow other ports we would need  extra parameters `--api-server-insecure-port` and `--api-server-secure-port` for render and start commands.

This would affect:
- temporary apiserver
- apiserver daemonset
- kubeconfig

**Comment by aaronlevy** [comment]
@odacremolbap it has been somewhat of a long-standing design decision not to plumb through most options into the render/start steps - because at some point we're just adding every flag available to k8s components into bootkube itself (and this quickly becomes untenable). 

Instead, we've split render/start into two distinct steps so that it is easy to modify the generated templates to your needs.

In this case it might not be as easy as simply modifying the rendered templates because the temporary control plane will operate at a different port. However, I am extremely hesitant to add any flags that require coordination between `render` and `start` - because that means you could have assets which only work if you happen to provide the correct flags to `start`, and this could easily cause users trouble.

I think to properly support something like this we might need to change to using static manifests for the temporary control plane (https://github.com/kubernetes-incubator/bootkube/issues/168). Then the process would allow for you to run `render` normally, but then you could go and modify the flags to both your temporary and self-hosted control plane and run `start` without any flags.

One thing to call out, however, is that the static manifest temporary control-plane makes other things difficult, so not immediately sure the best options here: https://github.com/kubernetes-incubator/bootkube/issues/168#issuecomment-279815328

Ultimately, until we have a good generic way of solving these problems - I am not very keen on adding flags to solve these problems - as it will make bootkube very difficult to test / maintain.

**Comment by odacremolbap** [comment]
agreed on #168

Thanks

**Comment by lblackstone** [comment]
@aaronlevy What do you think about changing the secure port to something other than 443? I ran into the same problem when trying to set up ingress, and got it working by updating all of the references to 6443.

**Comment by lblackstone** [comment]
Ping @aaronlevy 
I have the changes locally and can open a PR to change the default if you're 👍 to that.

**Comment by odacremolbap** [comment]
Hi @lblackstone 

I think this is being worked in a different direction. The control plane would no longer be an in-binary string but a rendered yaml, so we would be able to customize after the render stage.

see https://github.com/kubernetes-incubator/bootkube/issues/168

**Comment by aaronlevy** [comment]
Closing, as this can be customized in the temporary control-plane now
