### ISSUE TITLE
Should there be a "kubernetes-operator"?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [kubernetes-incubator/bootkube#361]
After watching the excellent talk at https://www.youtube.com/watch?v=Be1t2wTV0mE which included disaster recovery from various control plane outages, I wondered if it would make sense to also develop + deploy some kind of kubernetes operator (https://coreos.com/blog/introducing-operators.html) on top of a self-hosted kubernetes cluster.

One of the challenges would be that it needs to be able for example to start up temporary pods without relying on having a scheduler present. On the other hand, Bootkube then wouldn't even need to offer a running scheduler in the first place, if a kubernetes operator would be able to start on up anyways.

**Comment by aaronlevy** [comment]
I do think there will eventually be something along the lines of a kubernetes-operator - For example, it might be able to manage the upgrade of your cluster by rolling all the self-hosted manifests.

We will also need to build out some disaster recovery tooling - not sure if that will live directly in an operator running in the cluster (the cluster may be down) - but there's been a little bit of discussion about that:

https://github.com/kubernetes-incubator/bootkube/issues/112
https://github.com/kubernetes-incubator/bootkube/issues/333

**Comment by MarkusTeufelberger** [comment]
If such an operator would be able to recover from a full node failure, it might even be able to replace bootkube in the first place, since a deployment from scratch is no different than a full control plance outage, right?

**Comment by aaronlevy** [comment]
Briefly touched on in: https://github.com/kubernetes-incubator/bootkube/issues/333#issuecomment-282856357

But if you already have state (e.g. etcd data) then recovering from full control-plane outage it is different than deploying from scratch. Rather than generating assets (or using existing assets from disk) - the tool should extract what it needs directly from etcd so that it can start the temporary control-plane using all the same settings/data that was in the cluster prior.

**Comment by MarkusTeufelberger** [comment]
I agree, though a deployment from scratch would be just a special case with no (or minimal/static/initial/predefined) state needing to be recovered compared to a control plane outage with already accumulated state.
