### ISSUE TITLE
Use CNI pod to deploy CNI plugins to host filesystem

### ISSUE THREAD

**Issue by heschlie** [kubernetes-incubator/bootkube#405]
Raising this here at @aaronlevy request

We would like to push forward on using the host file system for the CNI binaries instead of the hyperkube file system.  This lets 3rd parties deploy the desired version of their CNI bin instead of relying on the version that is shipped with hyperkube.

This also creates some friction when deploying a CNI provider like Calico as the current standard operation is to change the `RKT_OPTS` in the kubelet to mount `/opt/cni/bin` in hyperkube to the host filesystem.  This seems sub-optimal as it wipes out the existing CNI binaries which then need to be redeployed.

**Comment by aaronlevy** [comment]
The general plan would be that the kubelet.service file would add a host volume mount of `/opt/cni/bin` which would be unpopulated at initialization. It would then be the responsibility of each network plugin to supply the required CNI plugins.

For each plugin, the podspec would need to include a host volume mount also for `/opt/cni/bin`. Then (maybe as a side-car container?) the pod would be responsible for copying the CNI plugin binary from the container filesystem into that hostmount, so that the binary is now available to the kubelet.

Some questions to be answered:

- How is the flannel CNI plugin distributed? (added to the flannel container fs, or kept separately?)
- How are "general" CNI plugins like IPAM/Bridge distributed? Are there container distributions of these?

I'm not immediately sure this is the route to take - but it does seem fairly reasonable.

**Comment by tomdee** [comment]
The flannel plugin is included in "general" plugins distribution so that might just answer that first question. The "official" CNI releases include a tarball and an ACI which could potentially be used as a side car container. If we can come up with a reasonable design I can help get it into upstream CNI if required.

**Comment by joshrosso** [comment]
This (mounting `/opt/cni/bin` in the kubelet) is the route I've taken for multiple Tectonic installs to achieve Canal.

Please let me know if I can be of any help in how it's been bootstrapped previously.

**Comment by mikebryant** [comment]
Some stuff we found out while figuring this out in our setup:
We currently have this for the kubelet:
```
          --volume=opt-cni,kind=host,source=/opt/cni,readOnly=true \
          --mount volume=opt-cni,target=/opt/weave-net \
```
and weave has this:
```
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
```

Turns out you can actually just put cni plugins in their own directory and it's capable of finding them: https://github.com/kubernetes/kubernetes/blob/7297403c69c5605a2728904a84d8216a2db673e5/pkg/kubelet/network/cni/cni.go#L39

**Comment by strowi** [comment]
@mikebryant is that just a finding or a workaround?
I wasn't able to deploy a new cluster with just putting the weave-yml into the manifest-folder and changing the kubelets-volumes?

**Comment by mikebryant** [comment]
weaveworks/weave#2613 is the upstream issue for weave support

What I posted above is how our weave + rkt/hyperkube setup is currently working, there's full manifests in the other issue, it's possible I missed something important out.

**Comment by aaronlevy** [comment]
I believe we started deploying CNI binaries via the daemonsets for flannel/calico in https://github.com/kubernetes-incubator/bootkube/pull/524 - so the original purpose of this issue I believe is satisfied (cc @abhinavdahiya)?

We could open a new issue to track support of weave if that's the remaining piece here.

**Comment by dghubble** [comment]
Yes, both flannel (possibly with policy-only calico) and calico (added by #714) use an `install-cni` sidecar to drop CNI plugins at `/opt/cni/bin` on the host, which the kubelet mounts. In fact, we now rely on this behavior since the default flannel config uses `portmap`, which is only installed on the host (rather than being in the hyperkube).

I think the original issue has been addressed. Adding weave as an option should be a separate issue now there is some precedent for picking the network provider.
