### ISSUE TITLE
Checkpoint env vars from configmaps/secrets

### ISSUE THREAD

**Issue by mikebryant** [kubernetes-incubator/bootkube#455]
This could just be done by rewriting the pod spec as it's saved, to pull in the current values of the configmap / secret fields.

(We were trying to use a configmap to add the same set of `--feature-gates` to all of our self-hosted components, and now our checkpointed pod doesn't work)

**Comment by aaronlevy** [comment]
One thing we would have to consider is if we do this for secrets, the pod manifest essentially becomes a secret as well -- and needs to be protected (putting your secret data into plain text inline of the manifest).

Not necessarily opposed to this (or maybe scoping down to configMaps). But this could get a bit complex / fragile doing a bunch of pod manifest rewrites (like we already do for secrets/configmap to hostmounts).  Also, depending on timing this might at least be mitigated by upcoming changes (albeit not until v1.7).

The plan moving forward is to move all flag configuration of core components into a configMap, then the components themselves can read a serialization of this from disk (which is populated by the configMap). So our checkpointing / rewriting of the configMap into a hostmount should work out-of-box.

As a side note - when we do finally get around to implementing real kubelet checkpointing, this is making me think we might need the kubelet to know about configMaps/secrets and how to populate them from checkpoints rather than trying to do a bunch of pod manifest translations.

**Comment by mikebryant** [comment]
Our main need for this is configmaps, I only added secrets as it seemed very related.
Your point is good though, I'd be happy leaving secrets out.

I think in the interim we'll just hardcode the apiserver one and have it live in two places, or have fun with sed, if we think this is just going to be solved for us in 1.7
