### ISSUE TITLE
etcd cluster TPR should be generated as part of the render step

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#476]
Rather than hard-coded: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/util/etcdutil/migrate.go#L121-L145

**Comment by diegs** [comment]
I can take this one if you'd like.

**Comment by aaronlevy** [comment]
@diegs sure - that would be great. It works -- just a bit of friction that likely is unnecessary

**Comment by diegs** [comment]
I started looking at this, and one unfortunate issue is that the TPR needs to specify the IP of the bootstrap etcd server to do the migration.

Since it's a static pod using host networking it's just the IP of the node that bootkube is running on, but we don't know *that* a priori either. I was thinking could either add another flag to `bootkube render` (ugh), or I could stand up a little service with a pre-determined IP that label selects the boot etcd. It's a little more complicated, but ultimately it is more flexible... (you could actually use this to migrate from an already running external etcd to a self-hosted etcd, for example)

**Comment by rimusz** [comment]
👍
