### ISSUE TITLE
Allow pod checkpointer to use different kubeconfig paths

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes-incubator/bootkube#625]
kubeadm doesn't save a standard `/etc/kubernetes/kubeconfig` file, but rather `/etc/kubernetes/admin.conf` and a series of specific component files. The problem is that the pod checkpointer expects the standard and already mounts `/etc/kubernetes` so you can't alias any of these files.

Also, will the checkpointer code ever live in its own repo?

**Comment by diegs** [comment]
The future of the checkpointer (esp. in regards to its use in `kubeadm`) is still being hashed out. Some relevant issues to look at/follow:

- https://github.com/kubernetes/kubeadm/issues/131
- https://github.com/kubernetes/kubernetes/issues/489
- https://github.com/kubernetes-incubator/bootkube/issues/424

Until that's resolved you may want to use a custom fork of the checkpointer for kubeadm development in the meantime.

**Comment by aaronlevy** [comment]
Per the sig-cluster-lifecycle meeting today, it seemed like there might again be a window in which `kubeadm` uses the podcheckpointer (rather than waiting on internal kubelet support of checkpointing). Prior to this I was still thinking `kubeadm` wasn't going to move forward with this approach.

However, if `kubeadm` does adopt using the pod-checkpointer, I sort of lean toward moving it into its own repo, maybe even follow the incubator process for checkpointer.

But even if we do that, I think we'll probably have to start adding flags to make it safe for shared/different use (e.g. kubeconfig location, annotations to use, etc.)
