### ISSUE TITLE
pod checkpointer should not store ports information for hostNetwork Pod

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/bootkube#646]
On node restart, there will be two copies of pod: the actual pod and the checkpointed one. The checkpointed pod will start first. If then the scheduler detects host port conflict, it will set the scheduled pod failed in APIServer, potentially delete the pod and affect service endpoints.

This is an issue for etcd pod so far. But it applies in general to other kinds of pods. Pod checkpointer should detect if a Pod is using hostNetwork and remove its ports field.

**Comment by aaronlevy** [comment]
Does the hostPort entry get added as part of defaulting logic (if hostNetwork) is set? Or did the pod start with the hostPort entry as part of the etcd pod manifest?

If it's the former, it's probably safe to strip the hostPort entry. But if a user explicitly sets the hostPort I'm not sure that's something we should be removing. And if the pod is successfully scheduled elsewhere, the checkpointer will clean up the old copy anyway.

**Comment by redbaron** [comment]
Facing similar problem: checkpointer cannot recover singlenode self hosted kluster when apiserver has `ports:  [{"containerPort":443"}] ` in it's definition.

Kubelet log has following:

```
Predicate failed on Pod: kube-apiserver-l2qtj_kube-system(ea6c66ac-d068-11e7-a85d-001000800010), for reason: Predicate PodFitsHostPorts failed
```

I guess even if user specified both ports & hostNetwork, then port info should be stripped when checkpointing, otherwise it is not recoverable
