### ISSUE TITLE
latest tag bootkube - docs recommend latest for recovery

### ISSUE THREAD

**Issue by sstarcher** [kubernetes-incubator/bootkube#647]
Would it make sense to publish a tagged image of the latest release?  The bootkube docs recommend using the latest bootkube version regardless of what version the cluster was created under.

https://github.com/kubernetes-incubator/bootkube/blob/8b303d78e723d65ec17c55e269551b7e7028bb54/Documentation/disaster-recovery.md#bootkube-recover

**Comment by aaronlevy** [comment]
@sstarcher we do publish images for all tagged releases: https://quay.io/repository/coreos/bootkube

And also have binary releases on the release page (I had forgotten for the last release initially, but the tarball should be there now).

**Comment by sstarcher** [comment]
But a latest tag is not published along with the tags.  So if a cluster is running and crashes and has a automated script that runs bootkube recovery it will likely use a hard tagged version such as `v0.5.0`, but your docs specify it is recommended to run whatever the latest tag is which is not an easy task with docker unless a `latest` or `stable` tag is published.

**Comment by aaronlevy** [comment]
Hmm. I'm initially hesitant about the idea of automatically running bootkube recovery. Recovering from backup shouldn't be a situation that is common.

What types of scenarios do you envision triggering the recovery process & how do you determine that it is a "crashed" state? e.g. re-migrating an etcd cluster that might have had a temporary network partition is a pretty heavy-handed approach (potential risk, loss of data between backup & recover, etc.). Versus having a human still inspect the cluster before deciding to run a recovery from backup).

**Comment by sstarcher** [comment]
@aaronlevy so the recommended approach is for an operator to lookup what the latest bootkube docker image is an pull that revision by hand?  I would prefer if the operator just ran a script instead of needing to go to an external source to look up the latest bootkube version.

Replace my statement about `automated` with just the idea that a human would run a predefined script.

**Comment by aaronlevy** [comment]
I see your point. My hesitancy there is that "latest" tags are often problematic (each run could have different behavior).

While there is some additional friction to looking up the latest release tag - it's also something where that release might need to be vetted against your tooling (e.g. maybe a flag changed). For example, when a new version of bootkube is released, recovery process is tested, then gets updated in your recovery scripts (and remains hard-coded until next release is vetted).

We recommend using the latest release right now, because the recovery tool was developing rather quickly - and there as of yet are no version dependencies. However, there's not to say that it could eventually become version dependent as well (e.g. recovery vX is recommended for v1.6-v1.9 kubernetes clusters).

I'll leave this open to track if we eventually do want to do this -- but i'm initially averse to using "latest" tags in general.

**Comment by sstarcher** [comment]
@aaronlevy I fully agree just the way the docs were written threw me off some.

**Comment by dghubble** [comment]
Suggestion:  Tweak docs to say "For best results, use the latest tagged bootkube [release](https://github.com/kubernetes-incubator/bootkube/releases)" and link to releases. Avoid publishing any image tagged "latest".
