### ISSUE TITLE
Restartability of bootkube

### ISSUE THREAD

**Issue by s-urbaniak** [kubernetes-incubator/bootkube#700]
This is mostly a question, @lucab and me have been wondering about. Currently, bootkube i.e. in Tectonic is used as one-shot service, see https://github.com/coreos/tectonic-installer/blob/25f4c76/modules/bootkube/resources/bootkube.service.

We were wondering if we could add any restart policy to the bootkube service, and here comes the question: Is bootkube designed/functional to cope with the situation that it can be stopped and restarted (possibly with an OS reboot in between)?

I don't believe that bootkube supports this mode of operation, but I may be wrong.

@aaronlevy: do you mind to give a little context or pointers on the above question? Thanks a lot in advance!

**Comment by aaronlevy** [comment]
It should hypothetically be safe to re-run bootkube (or re-run an interrupted execution) - as all it is really doing is injecting files into the cluster and waiting for them to exist.

If they already exist (e.g. re-running after interruption), it should ignore: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/bootkube/create.go#L121-L124

Or in some cases, creation of an object might fail based on something like service IP already in use (e.g. kube-dns service created again). In this case it gives warnings, but doesn't outright fail: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/bootkube/create.go#L39-L45

However, this is all behavior that is untested - ultimately bootkube is not meant to be run multiple times (but we should at least try to be somewhat idempotent).

The problems arise in a couple cases:

- self-hosted etcd I don't think this is as safe(and completely untested). This is largely because there are more coordination steps to the bootstrap instead of just "inject assets and wait". Now you're creating a new etcd cluster, then migrating data - and nothing checks if any of these steps have already/partially occurred. 

- leaving bootkube on a host and running it on every boot, for example, is out of the scope of intended use. This is because the assets bootkube uses on disk are going to become skewed from the assets that exist in the cluster. You don't want to upgrade a cluster then have bootkube try and create old assets from some random files that are sitting on disk. It's meant for "take this initial state on disk, and start a cluster with it - then get out of the way and never run again".

**Comment by coresolve** [comment]
we'd be ok on the reboot case cause we touch and test on a done file when the unit succeeds.
