### ISSUE TITLE
generate apiserver aggregation certs

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/bootkube#978]
Bootkube generates most of certs, it might as well generate aggregation API server certs using a separate CA as per docs: https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/

Example of implementation:

https://github.com/kubernetes/kubernetes/pull/47094/files

**Comment by ericchiang** [comment]
I'd prefer users do this and not add more functionality to `bootkube render`

**Comment by redbaron** [comment]
why? "bootkube render" creates set of files ready for a fully functional cluster, kubernetes is moving towards metrics-server  which runs using APIServer aggregation, it is just natural to have both new set of CA certs for aggregation.

If bootkube render was providing metrics-server in rendered manifests, would you consider adding CAs too?

**Comment by ericchiang** [comment]
> "bootkube render" creates set of files ready for a fully functional cluster

Render's goal is to provide us some basis for e2e testing. Bootkube itself isn't a distribution and we don't expect it to meet every use case. Bootkube users like [Typhoon](https://github.com/poseidon/terraform-render-bootkube) and [Tectonic](https://github.com/coreos/tectonic-installer/tree/1.8.4-tectonic.3/modules/bootkube) all do their own rendering because of this, and that's the way we'd like to encourage users to consume bootkube: to self-host clusters not to provide every manifest.

**Comment by redbaron** [comment]
Fair enough.
